import { useState, useMemo } from "react";
import { F } from "../../styles/palette";
import { DC, Bdg, Gauge, getSev } from "../shared";
import { LQ_ARM, LQ_LEG, LICF } from "../../data/lymqolData";

export default function DCVRS() {
  const [inst, setInst] = useState("lymqol");
  const [limb, setLimb] = useState("arm");
  const [lA, setLA] = useState({});
  const [iA, setIA] = useState({});
  const [aD, setAD] = useState(null);
  const D_ac = "#2dd4bf";
  const D_card = "rgba(15,23,42,0.65)";
  const doms = limb === "arm" ? LQ_ARM : LQ_LEG;

  const lS = useMemo(() => { const sc = {}; let ts = 0, tc = 0; Object.entries(doms).forEach(([dk, dom]) => { const v = dom.q.map((_, i) => lA[`${dk}_${i}`]).filter(Boolean); if (v.length) { sc[dk] = { avg: v.reduce((a, b) => a + b, 0) / v.length, ct: v.length, tot: dom.q.length }; ts += v.reduce((a, b) => a + b, 0); tc += v.length; } }); sc._ov = tc > 0 ? ts / tc : 0; sc._a = tc; sc._t = Object.values(doms).reduce((a, d) => a + d.q.length, 0); return sc; }, [lA, doms]);
  const iS = useMemo(() => { const sc = {}; let ts = 0, tc = 0; Object.entries(LICF).forEach(([dk, dom]) => { const v = dom.q.map((_, i) => iA[`${dk}_${i}`]).filter(Boolean); if (v.length) { sc[dk] = { avg: v.reduce((a, b) => a + b, 0) / v.length, ct: v.length, tot: dom.q.length, sum: v.reduce((a, b) => a + b, 0) }; ts += v.reduce((a, b) => a + b, 0); tc += v.length; } }); sc._tp = ts; sc._mp = 290; sc._pct = (ts/290)*100; sc._a = tc; sc._t = 29; return sc; }, [iA]);

  return <div>
    <div style={{ display: "flex", gap: 6, marginBottom: 12 }}>{[{ k: "lymqol", l: "LYMQOL (1-4)" },{ k: "icf", l: "Lymph-ICF (VAS 0-10)" }].map(x => <button key={x.k} onClick={() => { setInst(x.k); setAD(null); }} style={{ flex: 1, padding: 10, borderRadius: 8, border: `2px solid ${inst===x.k?D_ac:"rgba(100,116,139,0.12)"}`, background: inst===x.k?"rgba(45,212,191,0.1)":"rgba(15,23,42,0.5)", color: inst===x.k?D_ac:"#64748b", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: F.b }}>{x.l}</button>)}</div>

    {inst === "lymqol" && <>
      <div style={{ display: "flex", gap: 6, marginBottom: 12 }}>{[{ k: "arm", l: "Arm" },{ k: "leg", l: "Leg" }].map(x => <button key={x.k} onClick={() => { setLimb(x.k); setLA({}); setAD(null); }} style={{ padding: "5px 12px", borderRadius: 6, border: `1px solid ${limb===x.k?"#0284c7":"rgba(100,116,139,0.12)"}`, background: limb===x.k?"rgba(2,132,199,0.1)":"transparent", color: limb===x.k?"#0284c7":"#64748b", fontSize: 12, cursor: "pointer", fontWeight: 600 }}>{x.l}</button>)}<div style={{ marginLeft: "auto" }}><Bdg t={`${lS._a}/${lS._t}`} c="#0284c7" /></div></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>{Object.entries(doms).map(([dk, dom]) => { const sc = lS[dk], isA = aD===dk, sv = sc ? getSev(sc.avg,4) : null; return <div key={dk} onClick={() => setAD(isA?null:dk)} style={{ padding: 12, borderRadius: 10, cursor: "pointer", background: isA?`${dom.c}12`:D_card, border: `2px solid ${isA?dom.c:"rgba(100,116,139,0.1)"}` }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{dom.i}</span>{sc && <Bdg t={sc.avg.toFixed(1)} c={sv.c} />}</div><div style={{ fontWeight: 700, fontSize: 12, color: "#e2e8f0", marginTop: 5 }}>{dom.l}</div>{sc && <div style={{ fontSize: 10, color: sv.c, marginTop: 2, fontWeight: 600 }}>{sv.t}</div>}</div>; })}</div>
      {aD && doms[aD] && <DC title={`${doms[aD].i} ${doms[aD].l}`} accent={doms[aD].c}>{doms[aD].q.map((q, i) => <div key={i} style={{ padding: "8px 0", borderBottom: "1px solid rgba(100,116,139,0.06)" }}><p style={{ color: "#cbd5e1", fontSize: 13, margin: "0 0 6px" }}><span style={{ color: "#475569", fontSize: 11, fontFamily: F.m, marginRight: 5 }}>{i+1}.</span>{q}</p><div style={{ display: "flex", gap: 4 }}>{["Nada","Un poco","Bastante","Mucho"].map((l, j) => { const v=j+1, a=lA[`${aD}_${i}`]===v; const cs=["#16a34a","#ca8a04","#ea580c","#dc2626"]; return <button key={v} onClick={() => setLA(p => ({...p,[`${aD}_${i}`]:v}))} style={{ flex: 1, padding: "6px 2px", borderRadius: 6, fontSize: 11, fontWeight: a?700:500, border: `2px solid ${a?cs[j]:"rgba(100,116,139,0.1)"}`, background: a?`${cs[j]}15`:"rgba(30,41,59,0.4)", color: a?cs[j]:"#64748b", cursor: "pointer", fontFamily: F.b }}><div style={{ fontSize: 13, fontWeight: 800, fontFamily: F.m }}>{v}</div>{l}</button>; })}</div></div>)}</DC>}
      {lS._a > 0 && <DC title="Resultados LYMQOL" accent={D_ac}><div style={{ display: "flex", justifyContent: "space-around", gap: 8, marginBottom: 12 }}>{Object.entries(doms).map(([dk, dom]) => { const sc = lS[dk]; return sc ? <Gauge key={dk} v={sc.avg} max={4} label={dom.l} color={dom.c} sz={70} /> : null; })}</div><div style={{ textAlign: "center", padding: 12, background: "rgba(30,41,59,0.5)", borderRadius: 10 }}><div style={{ fontSize: 10, color: "#64748b" }}>Global</div><div style={{ fontSize: 26, fontWeight: 800, color: getSev(lS._ov,4).c, fontFamily: F.m }}>{lS._ov.toFixed(2)}</div><div style={{ fontSize: 12, color: getSev(lS._ov,4).c, fontWeight: 600 }}>{getSev(lS._ov,4).t}</div></div></DC>}
    </>}

    {inst === "icf" && <>
      <DC><p style={{ color: "#94a3b8", fontSize: 12, margin: 0 }}>29 items, VAS 0-10, 5 dominios. Cambio significativo: {"\u2265"}15 pts. Medida primaria RCT N-LVA 2024.</p><div style={{ marginTop: 5 }}><Bdg t={`${iS._a}/29`} c="#0284c7" /></div></DC>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>{Object.entries(LICF).map(([dk, dom]) => { const sc = iS[dk], isA = aD===dk, sv = sc ? getSev(sc.avg,10) : null; return <div key={dk} onClick={() => setAD(isA?null:dk)} style={{ padding: 12, borderRadius: 10, cursor: "pointer", background: isA?`${dom.c}12`:D_card, border: `2px solid ${isA?dom.c:"rgba(100,116,139,0.1)"}` }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{dom.i}</span>{sc && <Bdg t={sc.avg.toFixed(1)} c={sv.c} />}</div><div style={{ fontWeight: 700, fontSize: 12, color: "#e2e8f0", marginTop: 5 }}>{dom.l}</div>{sc && <div style={{ fontSize: 10, color: sv.c, marginTop: 2, fontWeight: 600 }}>{sv.t}</div>}</div>; })}</div>
      {aD && LICF[aD] && <DC title={`${LICF[aD].i} ${LICF[aD].l}`} accent={LICF[aD].c}>{LICF[aD].q.map((q, i) => { const v = iA[`${aD}_${i}`]||0; const gc = v<=2?"#16a34a":v<=4?"#ca8a04":v<=6?"#ea580c":v<=8?"#dc2626":"#991b1b"; return <div key={i} style={{ padding: "10px 0", borderBottom: "1px solid rgba(100,116,139,0.06)" }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 5 }}><p style={{ color: "#cbd5e1", fontSize: 13, margin: 0, flex: 1 }}><span style={{ color: "#475569", fontSize: 11, fontFamily: F.m, marginRight: 5 }}>{i+1}.</span>{q}</p><span style={{ color: gc, fontSize: 17, fontWeight: 800, fontFamily: F.m, marginLeft: 8 }}>{v}</span></div><input type="range" min={0} max={10} value={v} onChange={e => setIA(p => ({...p,[`${aD}_${i}`]:Number(e.target.value)}))} style={{ width: "100%", accentColor: gc, height: 5 }} /></div>; })}</DC>}
      {iS._a > 0 && <DC title="Resultados Lymph-ICF" accent="#8b5cf6">{Object.entries(LICF).map(([dk, dom]) => { const s = iS[dk]; if (!s) return null; const pct = (s.avg/10)*100, sv = getSev(s.avg,10); return <div key={dk} style={{ marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}><span style={{ color: "#cbd5e1", fontSize: 12, fontWeight: 600 }}>{dom.i} {dom.l}</span><span style={{ color: sv.c, fontSize: 13, fontWeight: 800, fontFamily: F.m }}>{s.avg.toFixed(1)}</span></div><div style={{ height: 7, background: "rgba(30,41,59,0.8)", borderRadius: 4, overflow: "hidden" }}><div style={{ height: "100%", width: `${pct}%`, background: dom.c, borderRadius: 4 }} /></div></div>; })}<div style={{ textAlign: "center", padding: 14, background: "rgba(30,41,59,0.5)", borderRadius: 10, marginTop: 6 }}><div style={{ fontSize: 10, color: "#64748b" }}>Total</div><div style={{ fontSize: 24, fontWeight: 800, color: "#e2e8f0", fontFamily: F.m }}>{iS._tp}<span style={{ fontSize: 13, color: "#475569" }}>/290</span></div><div style={{ fontSize: 16, fontWeight: 700, color: getSev(iS._pct/10,10).c, fontFamily: F.m }}>{iS._pct.toFixed(1)}%</div></div></DC>}
    </>}
  </div>;
}
